# Generated by Django 3.2.15 on 2022-09-20 13:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StopMotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(blank=True, max_length=1024, null=True)),
                ('Title', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField()),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
