# Generated by Django 3.2.15 on 2022-09-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stopmotion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stopmotion',
            old_name='Title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='stopmotion',
            name='image',
        ),
    ]
